<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.9.38">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="description" content="This book introduces the concepts of causal inference from a beginner’s perspective and leads the interested reader to numerous approaches to answer counterfactual questions using computational methods in R and Stata.">

<title>8&nbsp; Sensitivity analysis – Computational Causal Inference for Applied Researchers</title>
<style>
/* Default styles provided by pandoc.
** See https://pandoc.org/MANUAL.html#variables-for-html for config info.
*/
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
html { -webkit-text-size-adjust: 100%; }
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="../../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../../site_libs/clipboard/clipboard.min.js"></script>
<script src="../../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../../site_libs/quarto-search/fuse.min.js"></script>
<script src="../../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../../">
<link href="../../chapters/chapter9/index.html" rel="next">
<link href="../../chapters/chapter7/index.html" rel="prev">
<link href="../../figures/logo.png" rel="icon" type="image/png">
<script src="../../site_libs/quarto-html/quarto.js" type="module"></script>
<script src="../../site_libs/quarto-html/tabsets/tabsets.js" type="module"></script>
<script src="../../site_libs/quarto-html/popper.min.js"></script>
<script src="../../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../../site_libs/quarto-html/anchor.min.js"></script>
<link href="../../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../../site_libs/quarto-html/quarto-syntax-highlighting-15634bcf2e68342d4ad2dfa704d543f6.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../../site_libs/bootstrap/bootstrap-95edd58b3b27b9774827898c46d4f452.min.css" rel="stylesheet" append-hash="true" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>
<style>html{ scroll-behavior: smooth; }</style>
<script>
MathJax = {
  tex: {
    macros: {
      btheta: "\\boldsymbol{\\theta}",
      bbeta: "\\boldsymbol{\\beta}",
      bmu: "\\boldsymbol{\\mu}",
      bSigma: "\\boldsymbol{\\Sigma}",
      bx: "\\mathbf{x}",
      bX: "\\mathbf{X}",
      by: "\\mathbf{y}",
      bY: "\\mathbf{Y}",
      bU: "\\mathbf{U}",
      E: "\\mathbb{E}",
      Var: ["\\operatorname{Var}"],
      Cov: ["\\operatorname{Cov}"],
      Corr: ["\\operatorname{Corr}"],
      iid: "\\stackrel{\\text{i.i.d.}}{\\sim}",
      tendD: "\\stackrel{\\mathcal{D}}{\\longrightarrow}",
      reals: "\\mathbb{R}",
      PP: "\\mathbb{P}",
      P: "\\mathbb{P}",
      I: "\\mathbb{I}",
      A: "\\mathbb{A}",
      SE: ["\\operatorname{SE}"],
      SD: ["\\operatorname{SD}"],
      MSE: ["\\operatorname{MSE}"],
      argmax: ["\\operatorname{argmax}"],
      argmin: ["\\operatorname{argmin}"],
      logit: ["\\operatorname{logit}"],
      expit: ["\\operatorname{expit}"],
      odds: ["\\operatorname{odds}"],
      Pr: ["\\operatorname{Pr}"],
      indep: "\\perp\\!\\!\\!\\perp"
    }
  }
};
</script>

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script defer="" src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN" && texText && texText.data) {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../../styles.css">
</head>

<body class="nav-sidebar floating quarto-light">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" role="button" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../chapters/chapter8/index.html">Sensitivity Analysis &amp; Discussion</a></li><li class="breadcrumb-item"><a href="../../chapters/chapter8/index.html"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Sensitivity analysis</span></a></li></ol></nav>
        <a class="flex-grow-1" role="navigation" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="Search" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="../../">Computational Causal Inference for Applied Researchers</a> 
        <div class="sidebar-tools-main tools-wide">
    <a href="https://github.com/migariane/Causal-Inference-Book" title="Source Code" class="quarto-navigation-tool px-1" aria-label="Source Code"><i class="bi bi-github"></i></a>
    <a href="../../Computational-Causal-Inference-for-Applied-Researchers.pdf" title="Download PDF" class="quarto-navigation-tool px-1" aria-label="Download PDF"><i class="bi bi-file-pdf"></i></a>
    <div class="dropdown">
      <a href="" title="Share" id="quarto-navigation-tool-dropdown-0" class="quarto-navigation-tool dropdown-toggle px-1" data-bs-toggle="dropdown" aria-expanded="false" role="link" aria-label="Share"><i class="bi bi-share"></i></a>
      <ul class="dropdown-menu" aria-labelledby="quarto-navigation-tool-dropdown-0">
          <li>
            <a class="dropdown-item sidebar-tools-main-item" href="https://twitter.com/intent/tweet?url=|url|">
              <i class="bi bi-twitter pe-1"></i>
            Twitter
            </a>
          </li>
          <li>
            <a class="dropdown-item sidebar-tools-main-item" href="https://www.linkedin.com/sharing/share-offsite/?url=|url|">
              <i class="bi bi-linkedin pe-1"></i>
            LinkedIn
            </a>
          </li>
      </ul>
    </div>
</div>
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Preface</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true">
 <span class="menu-text">Foundations</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/chapter1/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">1</span>&nbsp; <span class="chapter-title">Introduction</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/chapter2/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">2</span>&nbsp; <span class="chapter-title">Regression adjustment</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true">
 <span class="menu-text">G-Methods</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/chapter3/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">3</span>&nbsp; <span class="chapter-title">G-formula</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/chapter4/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">4</span>&nbsp; <span class="chapter-title">Methods Based on the Propensity Score</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true">
 <span class="menu-text">Advanced Methods</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/chapter5/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">5</span>&nbsp; <span class="chapter-title">Double-robust estimators</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/chapter6/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">6</span>&nbsp; <span class="chapter-title">Causal Inference for Longitudinal Data</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/chapter7/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Mediation Analysis</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true">
 <span class="menu-text">Sensitivity Analysis &amp; Discussion</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" role="navigation" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/chapter8/index.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Sensitivity analysis</span></span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../chapters/chapter9/index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Discussion</span></span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../../references.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">References</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#overview-of-methods-for-sensitivity-analysis-in-causal-inference" id="toc-overview-of-methods-for-sensitivity-analysis-in-causal-inference" class="nav-link active" data-scroll-target="#overview-of-methods-for-sensitivity-analysis-in-causal-inference"><span class="header-section-number">8.1</span> Overview of methods for sensitivity analysis in causal inference</a></li>
  <li><a href="#the-e-value" id="toc-the-e-value" class="nav-link" data-scroll-target="#the-e-value"><span class="header-section-number">8.2</span> The E-value</a></li>
  <li><a href="#conditional-c-dependence" id="toc-conditional-c-dependence" class="nav-link" data-scroll-target="#conditional-c-dependence"><span class="header-section-number">8.3</span> Conditional c-dependence</a></li>
  <li><a href="#conclusion" id="toc-conclusion" class="nav-link" data-scroll-target="#conclusion"><span class="header-section-number">8.4</span> Conclusion</a></li>
  <li><a href="#glossary" id="toc-glossary" class="nav-link" data-scroll-target="#glossary"><span class="header-section-number">8.5</span> Glossary</a></li>
  </ul>
<div class="toc-actions"><ul><li><a href="https://github.com/migariane/Causal-Inference-Book/edit/main/chapters/chapter8/index.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/migariane/Causal-Inference-Book/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li><li><a href="https://github.com/migariane/Causal-Inference-Book/blob/main/chapters/chapter8/index.qmd" class="toc-action"><i class="bi empty"></i>View source</a></li></ul></div></nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../../chapters/chapter8/index.html">Sensitivity Analysis &amp; Discussion</a></li><li class="breadcrumb-item"><a href="../../chapters/chapter8/index.html"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Sensitivity analysis</span></a></li></ol></nav>
<div class="quarto-title">
<h1 class="title"><span id="sec-sensitivity" class="quarto-section-identifier"><span class="chapter-number">8</span>&nbsp; <span class="chapter-title">Sensitivity analysis</span></span></h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<p>In the process of causal inference, we frequently try to estimate the population effect of a binary treatment on an outcome variable by comparing the means of potential outcomes <span class="math inline">\(Y(1)\)</span>and<span class="math inline">\(Y(0)\)</span>, where <span class="math inline">\(Y(t)\)</span>is the (bounded) outcome of a random individual under treatment<span class="math inline">\(A\)</span>, <span class="citation" data-cites="neyman23app rubin74potential">(<a href="#ref-neyman23app" role="doc-biblioref">Neyman, 1923</a>; <a href="#ref-rubin74potential" role="doc-biblioref">Rubin, 1974</a>)</span>.” This contrast, known as the <em>Average Treatment Effect (ATE)</em>, must be identified from observational data (i.e., non-experimental investigations) based on untestable hypotheses, i.e., consistency, conditional ignorability, exchangeability or independence, and positivity. Under these assumptions, the ATE is identified from the observed data distribution via the <em>g formula</em>: <span class="math display">\[
\begin{aligned}
\textit{ATE} &amp;= \int_w \Big\{E[Y \mid A=1, \textbf{W=w}] - E[Y \mid A=0, \textbf{W=w}] \Big\} dF(w),
\end{aligned}
\]</span> {#eq-ace}</p>
<p>where <span class="math inline">\(F(\cdot)\)</span>denotes the cumulative distribution function of<span class="math inline">\(w\)</span>.</p>
<p>Using <span class="math inline">\(n\)</span>independent and identically distributed copies of<span class="math inline">\(O=(W, A, Y)\)</span>, many methods have been developed to draw inference about the ATE functional, e.g., propensity score matching <span class="citation" data-cites="rosenbaum83propensity">(<a href="#ref-rosenbaum83propensity" role="doc-biblioref">Rosenbaum &amp; Rubin, 1983</a>)</span>, g-computation <span class="citation" data-cites="robins86new">(<a href="#ref-robins86new" role="doc-biblioref">Robins, 1986</a>)</span>, (stabilized) inverse probability weighting <span class="citation" data-cites="hernan2006estimating">(<a href="#ref-hernan2006estimating" role="doc-biblioref">Hernán &amp; Robins, 2006</a>)</span>, augmented inverse probability weighting <span class="citation" data-cites="robins94estimation">(<a href="#ref-robins94estimation" role="doc-biblioref">Robins et al., 1994</a>)</span>, and targeted maximum likelihood <span class="citation" data-cites="van2006targeted">(<a href="#ref-van2006targeted" role="doc-biblioref">Der Laan &amp; Rubin, 2006</a>)</span> as seen in the previous chapters.</p>
<p>The conditional <em>conditional independence assumption</em> states that there exists a set of measured pre-treatment covariates (<strong>W</strong>) such that treatment is conditionally independent of the potential outcomes given <strong>W</strong>, i.e., <span id="eq-ci"><span class="math display">\[
Y(a) \perp A \mid \textbf{W} \quad \text{ for } a=0,1;
\tag{8.1}\]</span></span></p>
<p>implies that there are no unmeasured confounders (<strong>U</strong>) between treatment and outcome.</p>
<p>In sensitivity analysis from observational studies targeting the study of causal relationships, the robustness of inference to potential unmeasured confounding is always needed and considered crucial. In this chapter, we aim to briefly review the literature on sensitivity analysis in causal inference and provide a computational overview of the current methods for evaluating the sensitivity of the analysis to the unmeasured confounding assumption about the ATE (<a href="#eq-ci" class="quarto-xref">Equation&nbsp;<span class="quarto-unresolved-ref">eq-ci</span></a>).</p>
<section id="overview-of-methods-for-sensitivity-analysis-in-causal-inference" class="level2" data-number="8.1">
<h2 data-number="8.1" class="anchored" data-anchor-id="overview-of-methods-for-sensitivity-analysis-in-causal-inference"><span class="header-section-number">8.1</span> Overview of methods for sensitivity analysis in causal inference</h2>
<p>To investigate the effect of residual unmeasured confounding on the causal effect estimate, sensitivity analysis to the “no unmeasured confounders” assumption is commonly used. <span class="citation" data-cites="ding2016sensitivity">(<a href="#ref-ding2016sensitivity" role="doc-biblioref">Ding &amp; VanderWeele, 2016</a>)</span> Assessing how robust an estimated causal effect is to potential unmeasured confounding is the principal aim of the following methods.</p>
<p>The E-value was first introduced <span class="citation" data-cites="ding2016sensitivity">(<a href="#ref-ding2016sensitivity" role="doc-biblioref">Ding &amp; VanderWeele, 2016</a>)</span>. The authors proposed a sensitivity analysis technique without any assumptions about the unmeasured confounders. They derived a bound on the relative risk (RR) scale based on two parameters. However, the method does not accommodate complex measured confounders.</p>
<p><span class="citation" data-cites="Masten24">L. Z. Matthew A. Masten Alexandre Poirier (<a href="#ref-Masten24" role="doc-biblioref">2024</a>)</span> introduced a nonparametric methodology to evaluate the sensitivity of results related to causal inference under the assumption of conditional independence. He introduced the concept of <em>conditional partial independence</em>, which is a less stringent condition than full conditional independence. Specifically, he examined a group of assumptions labeled <em>conditional c-dependence</em>, which quantify the relaxation of conditional independence through a single parameter, c.&nbsp;For every positive c, conditional independence is only partially fulfilled, preventing the exact determination of treatment effect parameters, such as the ATE; instead, only bounds can be derived. Masten describes these bounds in relation to c: smaller c values result in tighter bounds, whereas larger c values produce broader bounds. The extent of these bounds, and thus the sensitivity of the results, is contingent upon the data.</p>
<p>Rosenbaum’s <span class="citation" data-cites="rosenbaum1987sensitivity">(<a href="#ref-rosenbaum1987sensitivity" role="doc-biblioref">Rosenbaum, 1987</a>)</span> method identified the smallest <span class="math inline">\(\Gamma\)</span> ensuring the ATE cannot be deemed “statistically significant” within matched studies <span class="citation" data-cites="tan2006distributional">(<a href="#ref-tan2006distributional" role="doc-biblioref">Tan, 2006</a>)</span>, and Zhao et al. <span class="citation" data-cites="zhao2019sensitivity">(<a href="#ref-zhao2019sensitivity" role="doc-biblioref">Zhao et al., 2019</a>)</span> established ATE bounds by comparing the odds of receiving treatment with both measured and unmeasured confounders versus only measured confounders. Recent advancements by Dorn et al. <span class="citation" data-cites="dorn2022sharp dorn2021doubly">(<a href="#ref-dorn2021doubly" role="doc-biblioref">Dorn et al., 2021</a>; <a href="#ref-dorn2022sharp" role="doc-biblioref">Dorn &amp; Guo, 2022</a>)</span> have further refined these bounds. The final bounds are expressed in a closed form, incorporating the observed propensity score, a specific transformed-outcome regression, and conditional quantiles of the outcome given treatment and covariates.</p>
<p>Moreover, <span class="citation" data-cites="dorn2021doubly">(<a href="#ref-dorn2021doubly" role="doc-biblioref">Dorn et al., 2021</a>)</span> demonstrated that estimators for these bounds can be developed that remain valid—though somewhat conservative—even when the conditional quantiles are improperly specified, provided that at least one of the other two nuisance functions is estimated consistently. Other methods, such as those described by <span class="citation" data-cites="diaz2013sensitivity">(<a href="#ref-diaz2013sensitivity" role="doc-biblioref">Dı́az &amp; Laan, 2013</a>)</span> and <span class="citation" data-cites="diaz2018sensitivity">(<a href="#ref-diaz2018sensitivity" role="doc-biblioref">Dı́az et al., 2018</a>)</span>, involve deriving bounds on the Average Treatment Effect (ATE) by limiting the difference in mean potential outcomes between patients who received treatment and those who received control, considering covariates. <span class="citation" data-cites="bonvini2022sensitivity">(<a href="#ref-bonvini2022sensitivity" role="doc-biblioref">Bonvini &amp; Kennedy, 2022</a>)</span> utilized a contamination model to provide bounds on the ATE by limiting the fraction of units influenced by unmeasured confounding. The following two sections focus on the E-value (developed in both Stata and R statistical software) and the Conditional C-dependence (only available in Stata) from a computationally applied perspective.</p>
</section>
<section id="the-e-value" class="level2" data-number="8.2">
<h2 data-number="8.2" class="anchored" data-anchor-id="the-e-value"><span class="header-section-number">8.2</span> The E-value</h2>
<p>The E-value is the minimum strength of a causal effect, on the RR scale, that an unmeasured confounder would need to have with both the treatment (E) and the outcome (D) to fully explain away a specific treatment-outcome association, conditional on the measured covariate (note that before we defined the treatment or exposure as (A) and the outcome as (Y). We decide to introduce here E and D to match the software convenctions further presented in this section). The E-value makes no assumptions on whether the unmeasured confounders (U) are binary, continuous, or categorical, on how they are distributed, or on the number of confounders, and it can be applied to several common outcome types and estimands in observational research. A large E-value implies that considerable unmeasured confounding would be needed to explain away an effect estimate. A small E-value implies little unmeasured confounding would be needed to explain away an effect estimate. Further developments <span class="citation" data-cites="vanderweele2011bias">(<a href="#ref-vanderweele2011bias" role="doc-biblioref">VanderWeele &amp; Arah, 2011</a>)</span> introduced a general “bias” formula for the difference between the possibly incorrect expression for the ATE under no unmeasured confounding and the correct expression for the ATE when accounting for both measured and unmeasured confounding in terms of many sensitivity parameters.</p>
<p>To facilitate these sensitivity analyses, an R package (“EValue”)<span class="citation" data-cites="Mathur2018">(<a href="#ref-Mathur2018" role="doc-biblioref">Maya B. Mathur, 2018</a>)</span> was developed and also an online E-value calculator is online available at <a href="https://mmathur.shinyapps.io/evalue/">https://mmathur.shinyapps.io/evalue/</a> that computes E-values for a variety of outcome measures.</p>
<p>The E-value seminal publication considered the historical study conducted by Hammond and Horn<span class="citation" data-cites="Hammond1958">(<a href="#ref-Hammond1958" role="doc-biblioref">Hammond, 1958</a>)</span> as an example to describe it. The study focused on the tobacco effect on lung cancer with a point estimate of the observed RR of cigarette smoking on lung cancer of 10.73 (95% CI 8.02, 14.36). Based on it we will illustrate the use of the R package to evaluate the effect of a common genetic confounder (U) on the observed RR of the treatment or exposure (E) on the outcome (D) using a set of boxes including the code and a detailed commented explanation.</p>
<p><strong>Box 8.1 (R):</strong> E-value for shifting a binary exposure under different scenarios</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="co"># You can install the EValue from CRAN using:</span></span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">"EValue"</span>)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="co"># Then, load the package:</span></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(EValue)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a><span class="co"># The E-value for the association between cigarette smoking and lung cancer as observed by Hammond and Horn in 1958 can be computed as follows:</span></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="fu">evalues.RR</span>(<span class="at">est =</span> <span class="fl">10.73</span>, <span class="at">lo =</span> <span class="fl">8.02</span>, <span class="at">hi =</span> <span class="fl">14.36</span>)</span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt;             point    lower upper</span></span>
<span id="cb1-8"><a href="#cb1-8" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; RR       10.73000  8.02000 14.36</span></span>
<span id="cb1-9"><a href="#cb1-9" aria-hidden="true" tabindex="-1"></a><span class="co">#&gt; E-values 20.94777 15.52336    NA</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>The E-value of 20.95 tells us that a confounder, or set of confounders (U), would have to be associated with a 20-fold increase in the risk of lung cancer and must be 20 times more prevalent in smokers than non-smokers to explain the observed RR. If the strength of one of these relationships were weaker, the other would have to be stronger for the causal effect of smoking on lung cancer to be truly null.</p>
<p>The package provides a plot functionality that allows the user to see how the magnitude of the exposure-confounder and the confounder-outcome relationships would have to vary to fully explain the observed association.</p>
<p><strong>Box 8.2 (R):</strong> Computing E-value with bias, confounding, and selection parameters</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">bias_plot</span>(<span class="fl">10.73</span>, <span class="at">xmax =</span> <span class="dv">40</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div id="fig-e-value-upper-bound" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-e-value-upper-bound-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="figures/Evalue.png" class="img-fluid quarto-figure quarto-figure-center figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-e-value-upper-bound-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;8.1: E-value upper bound
</figcaption>
</figure>
</div>
<p>This tells us, for example, that if the exposure-confounder parameter <span class="math inline">\(RR_{EU}\)</span>were 15, meaning that the confounder(s) is 15 times more likely among smokers, the<span class="math inline">\(RR_{UD}\)</span> for the confounder outcome relationship parameter would have to be about 40 for it to even be possible that confounding explains the entire observed association.</p>
<p>It is also possible to plot the lower bound of the confidence interval</p>
<p><strong>Box 8.3 (R):</strong> Plotting the E-value as a function of risk ratio</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="fu">bias_plot</span>(<span class="fl">8.02</span>, <span class="at">xmax =</span> <span class="dv">40</span>)</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>which we calculated an E-value of 15.52 for the above.</p>
<div id="fig-e-value-lower-bound" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-e-value-lower-bound-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="figures/Evalue2.png" class="img-fluid quarto-figure quarto-figure-center figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-e-value-lower-bound-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;8.2: E-value lower bound
</figcaption>
</figure>
</div>
<p>Scholars may evaluate the potential for confounding influences to alter the observed relationship to any other value, such as diminishing the observed relationship to a true causal effect that lacks scientific significance or amplifying a near-null observed relationship to one of scientific importance. For instance, to adjust an observed relative risk of 3.5 down to a true causal relative risk of 2.5, the E-value is 2.15. This represents the smallest amount of unmeasured confounding necessary to shift both the estimate and confidence interval toward your defined true value instead of the null value (Box 8.4).</p>
<p><strong>Box 8.4 (R):</strong> Computing the E-value from observed risk ratio and CI limits</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co"># summary() used to print the E-value only</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(<span class="fu">evalues.RR</span>(<span class="at">est =</span> <span class="fl">3.5</span>, <span class="at">true =</span> <span class="fl">2.5</span>))</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a><span class="co">#[1] 2.148331</span></span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>The E-value for the association between cigarette smoking and lung cancer as observed by Hammond and Horn in 1958 can be computed in Stata as follows <span class="citation" data-cites="Linden2020">(<a href="#ref-Linden2020" role="doc-biblioref">Ariel Linden, 2020</a>)</span>:</p>
<p><strong>Box 8.5 (Stata):</strong> Computing the E-value in Stata</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb5"><pre class="sourceCode stata code-with-copy"><code class="sourceCode stata"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>evalue rr 10.73, lcl(8.02) ucl(14.36) figure</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div id="fig-e-value-lower-upper-bounds-stata" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-e-value-lower-upper-bounds-stata-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="figures/Evalue3.png" class="img-fluid quarto-figure quarto-figure-center figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-e-value-lower-upper-bounds-stata-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;8.3: E-value lower and upper bounds in Stata
</figcaption>
</figure>
</div>
</section>
<section id="conditional-c-dependence" class="level2" data-number="8.3">
<h2 data-number="8.3" class="anchored" data-anchor-id="conditional-c-dependence"><span class="header-section-number">8.3</span> Conditional c-dependence</h2>
<p>In causal inference, a fundamental question is determining and estimating how a treatment variable <strong>A</strong> influences an outcome variable <strong>Y</strong>. A frequently adopted assumption for identifying these effects is unconfoundedness, also referred to as selection on observables, conditional independence, ignorability, or exogenous selection. This assumption is non-falsifiable, as the data itself cannot confirm its validity. However, researchers often question: How crucial is this assumption for their analyses? In other words, how robust are the results derived under the conditional independence assumption?</p>
<p>In their work, <span class="citation" data-cites="Masten18">(<a href="#ref-Masten18" role="doc-biblioref">A. P. Matthew A. Masten, 2018</a>)</span> present theoretical findings aimed at addressing this question. They introduce the concept of conditional partial independence, which is a relaxation of full conditional independence. The focus is on a specific type of assumption known as <strong>conditional c-dependence</strong>, quantifying deviations from conditional independence using a parameter c.&nbsp;When c is positive, conditional independence is only partial, preventing precise determination of treatment effect parameters such as ATE or ATT, resulting in bounded estimates instead. <span class="citation" data-cites="Masten18">(<a href="#ref-Masten18" role="doc-biblioref">A. P. Matthew A. Masten, 2018</a>)</span> describe these bounds as dependent on <strong>C</strong>, with smaller c leading to tighter bounds and larger c producing wider ones. The extent of these bounds, and thus the sensitivity of results, is influenced by the data. The paper by <span class="citation" data-cites="Masten24">(<a href="#ref-Masten24" role="doc-biblioref">L. Z. Matthew A. Masten Alexandre Poirier, 2024</a>)</span> explains the estimation strategy used from an applied computational perspective by using a Stata package named <strong>tesensitivity</strong>.</p>
<p>To define conditional c-dependence, we first define the following random variables:</p>
<ul>
<li><span class="math inline">\(Y^{a}\)</span>: the potential outcome for a given treatment<span class="math inline">\(a \in\{0,1\}\)</span></li>
<li><span class="math inline">\(A\)</span> : the treatment</li>
<li><span class="math inline">\(W\)</span> : a vector of covariates</li>
<li><span class="math inline">\(Y\)</span> : the observed outcome</li>
</ul>
<p>The observed outcome satisfies by consistency <span class="math display">\[
Y = (1-A) Y^{0} + A Y^{1}.
\]</span> Rather than observing the full data generating process, <span class="math inline">\((Y^{0}, Y^{1}, A, Y)\)</span>, we only observe: O=(Y, A, W).</p>
<p>We say that <span class="math inline">\(A\)</span>is conditionally c-dependent with<span class="math inline">\(Y^{a}\)</span>given<span class="math inline">\(W\)</span> if: <span class="math display">\[
\textbf{supp} \underset{y_{a} \in \operatorname{supp}(Y^{a}\mid W=w)}{\left|\mathbb{P}\left(A=1 \mid Y^{a}=a, W=w\right)-\mathbb{P}(A=1 \mid W=w)\right|} \leq c,
\]</span> for all <span class="math inline">\(w\)</span>in<span class="math inline">\(\operatorname{supp}(\mathbf{W})\)</span>.</p>
<p>Under this assumption, the identified set for a treatment effect statistic will be a closed interval, which depends on c and the distribution of O=(Y, A, W).</p>
<p>The main purpose of the <strong>tesensitivity</strong> package is to calculate these bounds and show how the identified set for treatment effect statistics i.e., ATE varies with the sensitivity parameter c.&nbsp;In addition to estimating these bounds for a range of values of c, <strong>tesensitivity</strong> also calculates a breakdown point relative to a conclusion about a treatment effect statistic i.e., the ATE. As discussed in <span class="citation" data-cites="Masten24">(<a href="#ref-Masten24" role="doc-biblioref">L. Z. Matthew A. Masten Alexandre Poirier, 2024</a>)</span>, the breakdown point is the maximum value of c under which the conclusion still holds.</p>
<p>Employing a Stata excerpt dataset from <span class="citation" data-cites="Cattaneo2010">(<a href="#ref-Cattaneo2010" role="doc-biblioref">Cattaneo, 2010</a>)</span> and <span class="citation" data-cites="almond2005costs">(<a href="#ref-almond2005costs" role="doc-biblioref">Almond et al., 2005</a>)</span>, alongside annotated boxes containing commented code, we demonstrate the computation and interpretation of the sensitivity parameter <span class="math inline">\(c\)</span> using the Stata package <strong>tesensitivity</strong>.</p>
<p>Treatment-effects modeling serves as a vital method for deriving causal effects akin to those from experiments, even when working with observational data. While conducting an experiment would be ideal, such endeavors are often impractical due to ethical or financial constraints. For instance, consider assessing the impact of cigarette smoking (the intervention) on infant birthweight (the resultant outcome). Ideally, an experiment would involve selecting a representative group of pregnant women, dividing them into a control group instructed not to smoke and a treatment group required to smoke a designated number of cigarettes each day.</p>
<p>Consider addressing this question by employing the Stata command <strong>teffects</strong>. To ensure our estimates are reliable, it is crucial to confirm that when we account for observable characteristics, it appears as though pregnant mothers were randomly distributed between control and treatment groups. We model the birthweight (bweight) as a function of the number of prenatal visits (nprenatal), whether the mother is married (mmarried), whether this baby is her first pregnancy (fbaby), and maternal education (medu). The treatment, smoking during pregnancy (mbsmoke), is modeled as a function of the same variables and concerning whether the mother consumed alcohol during her pregnancy. For reference, we start by estimating the ATE of these experimental and non-experimental samples based on maternal smoking using the <strong>eltmle</strong> Stata package. <span class="citation" data-cites="Luque-Fernandez2019">(<a href="#ref-Luque-Fernandez2019" role="doc-biblioref">Luque-Fernandez, 2019</a>)</span> (Box 8.6)</p>
<p><strong>Box 8.6 (Stata):</strong> ATE using teffects and eltmle</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb6"><pre class="sourceCode stata code-with-copy"><code class="sourceCode stata"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a># To allow intalling Stata programs from GitHub:</span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>    net install github, from(<span class="st">"https://haghish.github.io/github/"</span>)</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a># To install eltmle Stata <span class="kw">program</span> to compute the ATE:</span>
<span id="cb6-6"><a href="#cb6-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-7"><a href="#cb6-7" aria-hidden="true" tabindex="-1"></a>    github install migariane/eltmle</span>
<span id="cb6-8"><a href="#cb6-8" aria-hidden="true" tabindex="-1"></a>    which eltmle</span>
<span id="cb6-9"><a href="#cb6-9" aria-hidden="true" tabindex="-1"></a>    <span class="kw">help</span> eltmle</span>
<span id="cb6-10"><a href="#cb6-10" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-11"><a href="#cb6-11" aria-hidden="true" tabindex="-1"></a># These will <span class="kw">be</span> the <span class="kw">data</span> and variables used <span class="kw">in</span> the analysis:</span>
<span id="cb6-12"><a href="#cb6-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-13"><a href="#cb6-13" aria-hidden="true" tabindex="-1"></a>    <span class="kw">webuse</span> cattaneo2, <span class="kw">clear</span></span>
<span id="cb6-14"><a href="#cb6-14" aria-hidden="true" tabindex="-1"></a>    <span class="kw">describe</span></span>
<span id="cb6-15"><a href="#cb6-15" aria-hidden="true" tabindex="-1"></a>    <span class="kw">local</span> Y <span class="st">"bweight"</span></span>
<span id="cb6-16"><a href="#cb6-16" aria-hidden="true" tabindex="-1"></a>    <span class="kw">local</span> A <span class="st">"mbsmoke"</span></span>
<span id="cb6-17"><a href="#cb6-17" aria-hidden="true" tabindex="-1"></a>    <span class="kw">local</span> W <span class="st">"nprenatal mmarried fbaby medu"</span></span>
<span id="cb6-18"><a href="#cb6-18" aria-hidden="true" tabindex="-1"></a>    eltmle <span class="ot">`Y'</span> <span class="ot">`A'</span> <span class="ot">`W'</span>, tmle</span>
<span id="cb6-19"><a href="#cb6-19" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-20"><a href="#cb6-20" aria-hidden="true" tabindex="-1"></a># Output:</span>
<span id="cb6-21"><a href="#cb6-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-22"><a href="#cb6-22" aria-hidden="true" tabindex="-1"></a>    Variable |        Obs        Mean    Std. <span class="kw">dev</span>.       Min        Max</span>
<span id="cb6-23"><a href="#cb6-23" aria-hidden="true" tabindex="-1"></a>-------------+---------------------------------------------------------</span>
<span id="cb6-24"><a href="#cb6-24" aria-hidden="true" tabindex="-1"></a>        POM1 |      4,642    2843.307     114.191    2369.31   3539.972</span>
<span id="cb6-25"><a href="#cb6-25" aria-hidden="true" tabindex="-1"></a>        POM0 |      4,642    3061.247    150.1519   2453.428   3931.552</span>
<span id="cb6-26"><a href="#cb6-26" aria-hidden="true" tabindex="-1"></a>          ps |      4,642    .1861267    .1110024   .0368017   .6847253</span>
<span id="cb6-27"><a href="#cb6-27" aria-hidden="true" tabindex="-1"></a>--------------------------------</span>
<span id="cb6-28"><a href="#cb6-28" aria-hidden="true" tabindex="-1"></a>TMLE: Average Treatment Effect</span>
<span id="cb6-29"><a href="#cb6-29" aria-hidden="true" tabindex="-1"></a>--------------------------------</span>
<span id="cb6-30"><a href="#cb6-30" aria-hidden="true" tabindex="-1"></a>ATE:      | -217.9</span>
<span id="cb6-31"><a href="#cb6-31" aria-hidden="true" tabindex="-1"></a><span class="kw">SE</span>:       |   22.8</span>
<span id="cb6-32"><a href="#cb6-32" aria-hidden="true" tabindex="-1"></a>P-<span class="ot">value</span>:  | 0.0000</span>
<span id="cb6-33"><a href="#cb6-33" aria-hidden="true" tabindex="-1"></a>95%CI:    | -262.6, -173.3</span>
<span id="cb6-34"><a href="#cb6-34" aria-hidden="true" tabindex="-1"></a>--------------------------------</span>
<span id="cb6-35"><a href="#cb6-35" aria-hidden="true" tabindex="-1"></a>-----------------------------</span>
<span id="cb6-36"><a href="#cb6-36" aria-hidden="true" tabindex="-1"></a>TMLE: Causal Risk Ratio (CRR)</span>
<span id="cb6-37"><a href="#cb6-37" aria-hidden="true" tabindex="-1"></a>-----------------------------</span>
<span id="cb6-38"><a href="#cb6-38" aria-hidden="true" tabindex="-1"></a>CRR: 0.93; 95%CI:(0.91, 0.94)</span>
<span id="cb6-39"><a href="#cb6-39" aria-hidden="true" tabindex="-1"></a>-----------------------------</span>
<span id="cb6-40"><a href="#cb6-40" aria-hidden="true" tabindex="-1"></a>-------------------------------</span>
<span id="cb6-41"><a href="#cb6-41" aria-hidden="true" tabindex="-1"></a>TMLE: Marginal Odds Ratio (MOR)</span>
<span id="cb6-42"><a href="#cb6-42" aria-hidden="true" tabindex="-1"></a>-------------------------------</span>
<span id="cb6-43"><a href="#cb6-43" aria-hidden="true" tabindex="-1"></a>MOR: 0.84; 95%CI:(0.81, 0.87)</span>
<span id="cb6-44"><a href="#cb6-44" aria-hidden="true" tabindex="-1"></a>-------------------------------</span>
<span id="cb6-45"><a href="#cb6-45" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-46"><a href="#cb6-46" aria-hidden="true" tabindex="-1"></a># Using the Stata software command <span class="kw">for</span> causal inference and the augmented</span>
<span id="cb6-47"><a href="#cb6-47" aria-hidden="true" tabindex="-1"></a># inverse probability weights (AIPW) algorithm:</span>
<span id="cb6-48"><a href="#cb6-48" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-49"><a href="#cb6-49" aria-hidden="true" tabindex="-1"></a>    teffects aipw (<span class="ot">`Y'</span> <span class="ot">`W'</span>) (<span class="ot">`A'</span> <span class="ot">`W'</span>)</span>
<span id="cb6-50"><a href="#cb6-50" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-51"><a href="#cb6-51" aria-hidden="true" tabindex="-1"></a># Output:</span>
<span id="cb6-52"><a href="#cb6-52" aria-hidden="true" tabindex="-1"></a>Iteration 0:   EE criterion =  3.069e-23</span>
<span id="cb6-53"><a href="#cb6-53" aria-hidden="true" tabindex="-1"></a>Iteration 1:   EE criterion =  2.182e-25</span>
<span id="cb6-54"><a href="#cb6-54" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb6-55"><a href="#cb6-55" aria-hidden="true" tabindex="-1"></a>Treatment-<span class="kw">effects</span> estimation        Number <span class="kw">of</span> <span class="kw">obs</span>     =      4,642</span>
<span id="cb6-56"><a href="#cb6-56" aria-hidden="true" tabindex="-1"></a>Estimator      : augmented IPW</span>
<span id="cb6-57"><a href="#cb6-57" aria-hidden="true" tabindex="-1"></a>Outcome <span class="kw">model</span>  : linear <span class="kw">by</span> ML</span>
<span id="cb6-58"><a href="#cb6-58" aria-hidden="true" tabindex="-1"></a>Treatment <span class="kw">model</span>: <span class="kw">logit</span></span>
<span id="cb6-59"><a href="#cb6-59" aria-hidden="true" tabindex="-1"></a>------------------------------------------------------------------------------</span>
<span id="cb6-60"><a href="#cb6-60" aria-hidden="true" tabindex="-1"></a>             |               Robust</span>
<span id="cb6-61"><a href="#cb6-61" aria-hidden="true" tabindex="-1"></a>     bweight | Coefficient  <span class="fu">std</span>. err.      z    P&gt;|z|    [95% conf. interval]</span>
<span id="cb6-62"><a href="#cb6-62" aria-hidden="true" tabindex="-1"></a>-------------+----------------------------------------------------------------</span>
<span id="cb6-63"><a href="#cb6-63" aria-hidden="true" tabindex="-1"></a>ATE  mbsmoke |</span>
<span id="cb6-64"><a href="#cb6-64" aria-hidden="true" tabindex="-1"></a>   (1 vs 0)  |  -223.4343    24.3635    -9.17   0.000   -271.1858   -175.6827</span>
<span id="cb6-65"><a href="#cb6-65" aria-hidden="true" tabindex="-1"></a>-------------+----------------------------------------------------------------</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>The ATE is interpreted as the mean risk difference of 217.9 fewer grams in the birth weight from infants born to mothers who smoke vs.&nbsp;infants born from non-smoker mothers in an additive scale using eltmle and 223 fewer grams using the <strong>aipw</strong> Stata option from the <strong>teffects</strong> command.</p>
<p>Under the standard unconfoundedness assumption, the treatment effect is negative and statistically significant. Now we will use the <strong>tesensitivity</strong> package to analyze how sensitive these results are to this assumption. The main subcommand of the <strong>tesensitivity</strong> package is <strong>cpi</strong>, i.e., conditional partial independence. This command estimates bounds on the ATE given a set of c-dependence values and calculates the breakdown point for the conclusion that the treatment effect statistic is above a given threshold. First, we calculate bounds on the ATE. By default, the command calculates bounds for a uniform grid of 40 values of c, and the breakdown point for the conclusion that the ATE estimation does not contain the null.</p>
<p><strong>Box 8.7 (Stata):</strong> tesensitivity: bounds on ATE under conditional c-dependence</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb7"><pre class="sourceCode stata code-with-copy"><code class="sourceCode stata"><span id="cb7-1"><a href="#cb7-1" aria-hidden="true" tabindex="-1"></a># Running the command:</span>
<span id="cb7-2"><a href="#cb7-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-3"><a href="#cb7-3" aria-hidden="true" tabindex="-1"></a>    tesensitivity cpi (<span class="ot">`Y'</span> <span class="ot">`W'</span>) (<span class="ot">`A'</span> <span class="ot">`W'</span>), ate</span>
<span id="cb7-4"><a href="#cb7-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-5"><a href="#cb7-5" aria-hidden="true" tabindex="-1"></a># Output:</span>
<span id="cb7-6"><a href="#cb7-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb7-7"><a href="#cb7-7" aria-hidden="true" tabindex="-1"></a>Treatment <span class="kw">effects</span> sensitivity</span>
<span id="cb7-8"><a href="#cb7-8" aria-hidden="true" tabindex="-1"></a>Analysis         : <span class="fu">cond</span>. partial independence  Number <span class="kw">of</span> <span class="kw">obs</span>=         4642</span>
<span id="cb7-9"><a href="#cb7-9" aria-hidden="true" tabindex="-1"></a>Outcome <span class="kw">model</span>    : linear <span class="kw">quantile</span>           Breakdown      =         0.058</span>
<span id="cb7-10"><a href="#cb7-10" aria-hidden="true" tabindex="-1"></a>Treatment <span class="kw">model</span>  : <span class="kw">logistic</span>                  Conclusion     =         ate &gt; 0</span>
<span id="cb7-11"><a href="#cb7-11" aria-hidden="true" tabindex="-1"></a>Outcome <span class="kw">variable</span> : bweight</span>
<span id="cb7-12"><a href="#cb7-12" aria-hidden="true" tabindex="-1"></a>-------------------------------------</span>
<span id="cb7-13"><a href="#cb7-13" aria-hidden="true" tabindex="-1"></a>                 c |              ate</span>
<span id="cb7-14"><a href="#cb7-14" aria-hidden="true" tabindex="-1"></a>-------------------+-----------------</span>
<span id="cb7-15"><a href="#cb7-15" aria-hidden="true" tabindex="-1"></a>             0.000 | [  -220,   -220]</span>
<span id="cb7-16"><a href="#cb7-16" aria-hidden="true" tabindex="-1"></a>             0.026 | [  -309,   -134]</span>
<span id="cb7-17"><a href="#cb7-17" aria-hidden="true" tabindex="-1"></a>             0.051 | [  -414,    -38]</span>
<span id="cb7-18"><a href="#cb7-18" aria-hidden="true" tabindex="-1"></a>             0.077 | [  -587,    120]</span>
<span id="cb7-19"><a href="#cb7-19" aria-hidden="true" tabindex="-1"></a>             0.103 | [  -826,    317]</span>
<span id="cb7-20"><a href="#cb7-20" aria-hidden="true" tabindex="-1"></a>             0.128 | [-1,027,    493]</span>
<span id="cb7-21"><a href="#cb7-21" aria-hidden="true" tabindex="-1"></a>             0.154 | [-1,218,    629]</span>
<span id="cb7-22"><a href="#cb7-22" aria-hidden="true" tabindex="-1"></a>                    ...</span>
<span id="cb7-23"><a href="#cb7-23" aria-hidden="true" tabindex="-1"></a>             0.769 | [-2,475,  1,825]</span>
<span id="cb7-24"><a href="#cb7-24" aria-hidden="true" tabindex="-1"></a>             0.795 | [-2,487,  1,844]</span>
<span id="cb7-25"><a href="#cb7-25" aria-hidden="true" tabindex="-1"></a>             0.821 | [-2,500,  1,867]</span>
<span id="cb7-26"><a href="#cb7-26" aria-hidden="true" tabindex="-1"></a>             0.846 | [-2,511,  1,889]</span>
<span id="cb7-27"><a href="#cb7-27" aria-hidden="true" tabindex="-1"></a>             0.872 | [-2,518,  1,901]</span>
<span id="cb7-28"><a href="#cb7-28" aria-hidden="true" tabindex="-1"></a>             0.897 | [-2,523,  1,906]</span>
<span id="cb7-29"><a href="#cb7-29" aria-hidden="true" tabindex="-1"></a>             0.923 | [-2,524,  1,906]</span>
<span id="cb7-30"><a href="#cb7-30" aria-hidden="true" tabindex="-1"></a>             0.949 | [-2,524,  1,906]</span>
<span id="cb7-31"><a href="#cb7-31" aria-hidden="true" tabindex="-1"></a>             0.974 | [-2,524,  1,906]</span>
<span id="cb7-32"><a href="#cb7-32" aria-hidden="true" tabindex="-1"></a>             1.000 | [-2,524,  1,906]</span>
<span id="cb7-33"><a href="#cb7-33" aria-hidden="true" tabindex="-1"></a>-------------------------------------</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<p>The grid of values show that the breakdown point computation for c is 0.077. Remember that the breakdown point is the maximum value of c under which the conclusion still holds. For example, if we consider the conclusion that the ATE is negative as in our example, then the breakdown point is the minimum value of c such that 0 is included in the identified 95% CI for the ATE in the set. The package also includes tools to visualize the analysis, interpret the scale of c-dependence, and compare results of multiple sensitivity analyses. Note that the value of c is small indicating weak unconfoundeness assumption based on the observed data.</p>
<p><strong>Box 8.8 (Stata):</strong> tesensitivity visual tools: cpiplot</p>
<div class="code-copy-outer-scaffold"><div class="sourceCode" id="cb8"><pre class="sourceCode stata code-with-copy"><code class="sourceCode stata"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a>tesensitivity cpiplot</span></code></pre></div><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></div>
<div id="fig-conditional-c-dependence-breakdown-point" class="quarto-float quarto-figure quarto-figure-center anchored" data-fig-align="center">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-conditional-c-dependence-breakdown-point-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="figures/Cvalue4.png" class="img-fluid quarto-figure quarto-figure-center figure-img">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-conditional-c-dependence-breakdown-point-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;8.4: Conditional c-dependence: breakdown point
</figcaption>
</figure>
</div>
</section>
<section id="conclusion" class="level2" data-number="8.4">
<h2 data-number="8.4" class="anchored" data-anchor-id="conclusion"><span class="header-section-number">8.4</span> Conclusion</h2>
<p>Sensitivity analysis is an essential component of any causal inference from observational data. While methods such as the g-formula, IPW, and TMLE address confounding by measured covariates, the assumption of no unmeasured confounding is fundamentally untestable. Sensitivity analysis quantifies how robust study conclusions are to violations of this assumption.</p>
<p>This chapter has introduced three complementary approaches: - The <strong>E-value</strong> provides an intuitive, scale-free metric: the minimum strength of association an unmeasured confounder would need to have with both treatment and outcome to explain away the observed effect. Its simplicity makes it accessible to non-specialist audiences. - The <strong>conditional c-dependence</strong> approach, implemented in the <code>tesensitivity</code> package, offers a more flexible framework that conditions on measured covariates, providing refined bounds. - Both methods complement — rather than replace — careful study design, thorough confounder measurement, and rigorous primary analysis.</p>
<p>Key takeaways from this chapter: - No observational study can prove that all confounders have been measured. - Sensitivity analysis should be a routine part of any causal analysis, not an afterthought. - The E-value is easy to compute and report, making it suitable for transparent communication of uncertainty. - The conditional c-dependence approach provides tighter bounds by leveraging information on measured confounders. - Sensitivity analyses should be interpreted in the context of substantive knowledge about likely unmeasured confounders.</p>
</section>
<section id="glossary" class="level2" data-number="8.5">
<h2 data-number="8.5" class="anchored" data-anchor-id="glossary"><span class="header-section-number">8.5</span> Glossary</h2>
<dl>
<dt><strong>Breakdown point</strong></dt>
<dd>
The maximum value of a sensitivity parameter under which the study conclusion (e.g., a significant causal effect) still holds.
</dd>
<dt><strong>c-dependence</strong></dt>
<dd>
A measure of the strength of residual confounding, representing the deviation from the assumption of no unmeasured confounding.
</dd>
<dt><strong>E-value</strong></dt>
<dd>
The minimum strength of association, on the risk ratio scale, that an unmeasured confounder would need to have with both the treatment and the outcome to fully explain away an observed treatment-outcome association.
</dd>
<dt><strong>Sensitivity analysis</strong></dt>
<dd>
A set of methods for assessing how sensitive causal conclusions are to violations of untestable assumptions, particularly the assumption of no unmeasured confounding.
</dd>
<dt><strong>Unmeasured confounding</strong></dt>
<dd>
Confounding by variables that were not measured and therefore cannot be adjusted for in the analysis.
</dd>
</dl>


<div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" data-line-spacing="2" role="list">
<div id="ref-almond2005costs" class="csl-entry" role="listitem">
Almond, D., Chay, K. Y., &amp; Lee, D. S. (2005). The costs of low birth weight. <em>The Quarterly Journal of Economics</em>, <em>120</em>(3), 1031–1083.
</div>
<div id="ref-Linden2020" class="csl-entry" role="listitem">
Ariel Linden, T. J. V., Maya B. Mathur. (2020). Conducting sensitivity analysis for unmeasured confounding in observational studies using e-values: The evalue package. <em>The Stata Journal: Promoting Communications on Statistics and Stata</em>, <em>20</em>(1), 162–175. <a href="https://doi.org/10.1177/1536867x20909696">https://doi.org/10.1177/1536867x20909696</a>
</div>
<div id="ref-bonvini2022sensitivity" class="csl-entry" role="listitem">
Bonvini, M., &amp; Kennedy, E. H. (2022). Sensitivity analysis via the proportion of unmeasured confounding. <em>Journal of the American Statistical Association</em>, <em>117</em>(539), 1540–1550.
</div>
<div id="ref-Cattaneo2010" class="csl-entry" role="listitem">
Cattaneo, M. D. (2010). <span class="nocase">Efficient semiparametric estimation of multi-valued treatment effects under ignorability</span>. <em>Journal of Econometrics</em>, <em>155</em>(2), 138–154. <a href="https://econpapers.repec.org/RePEc:eee:econom:v:155:y:2010:i:2:p:138-154">https://econpapers.repec.org/RePEc:eee:econom:v:155:y:2010:i:2:p:138-154</a>
</div>
<div id="ref-van2006targeted" class="csl-entry" role="listitem">
Der Laan, M. J. van, &amp; Rubin, D. (2006). Targeted maximum likelihood learning. <em>The International Journal of Biostatistics</em>, <em>2</em>(1), Article 11.
</div>
<div id="ref-ding2016sensitivity" class="csl-entry" role="listitem">
Ding, P., &amp; VanderWeele, T. J. (2016). Sensitivity analysis without assumptions. <em>Epidemiology</em>, <em>27</em>(3), 368.
</div>
<div id="ref-diaz2013sensitivity" class="csl-entry" role="listitem">
Dı́az, I., &amp; Laan, M. J. van der. (2013). Sensitivity analysis for causal inference under unmeasured confounding and measurement error problems. <em>The International Journal of Biostatistics</em>, <em>9</em>(2), 149–160.
</div>
<div id="ref-diaz2018sensitivity" class="csl-entry" role="listitem">
Dı́az, I., Luedtke, A. R., &amp; Laan, M. J. van der. (2018). Sensitivity analysis. In <em>Targeted learning in data science</em> (pp. 511–522). Springer.
</div>
<div id="ref-dorn2022sharp" class="csl-entry" role="listitem">
Dorn, J., &amp; Guo, K. (2022). Sharp sensitivity analysis for inverse propensity weighting via quantile balancing. <em>Journal of the American Statistical Association</em>, 1–13.
</div>
<div id="ref-dorn2021doubly" class="csl-entry" role="listitem">
Dorn, J., Guo, K., &amp; Kallus, N. (2021). Doubly-valid/doubly-sharp sensitivity analysis for causal inference with unmeasured confounding. <em>arXiv Preprint arXiv:2112.11449</em>.
</div>
<div id="ref-Hammond1958" class="csl-entry" role="listitem">
Hammond, E. C. (1958). SMOKING AND DEATH RATES—REPORT ON FORTY-FOUR MONTHS OF FOLLOW-UP OF 187,783 MEN. <em>Journal of the American Medical Association</em>, <em>166</em>(11), 1294. <a href="https://doi.org/10.1001/jama.1958.02990110030007">https://doi.org/10.1001/jama.1958.02990110030007</a>
</div>
<div id="ref-hernan2006estimating" class="csl-entry" role="listitem">
Hernán, M. A., &amp; Robins, J. M. (2006). Estimating causal effects from epidemiological data. <em>Journal of Epidemiology &amp; Community Health</em>, <em>60</em>(7), 578–586.
</div>
<div id="ref-Luque-Fernandez2019" class="csl-entry" role="listitem">
Luque-Fernandez, M. A. (2019). <em><span class="nocase">migariane/meltmle: Ensemble Learning Targeted Maximum Likelihood Estimation for Stata users | Zenodo</span></em>. <a href="https://zenodo.org/record/2560828">https://zenodo.org/record/2560828</a>
</div>
<div id="ref-Masten18" class="csl-entry" role="listitem">
Matthew A. Masten, A. P. (2018). Identification of treatment effects under conditional partial independence. <em>Econometrica</em>, <em>86</em>(1), 317–351. <a href="https://doi.org/10.3982/ecta14481">https://doi.org/10.3982/ecta14481</a>
</div>
<div id="ref-Masten24" class="csl-entry" role="listitem">
Matthew A. Masten, L. Z., Alexandre Poirier. (2024). Assessing sensitivity to unconfoundedness: Estimation and inference. <em>Journal of Business &amp;Amp; Economic Statistics</em>, <em>42</em>(1), 1–13. <a href="https://doi.org/10.1080/07350015.2023.2183212">https://doi.org/10.1080/07350015.2023.2183212</a>
</div>
<div id="ref-Mathur2018" class="csl-entry" role="listitem">
Maya B. Mathur, C. A. R., Peng Ding. (2018). Web site and r package for computing e-values. <em>Epidemiology</em>, <em>29</em>(5), e45–e47. <a href="https://doi.org/10.1097/ede.0000000000000864">https://doi.org/10.1097/ede.0000000000000864</a>
</div>
<div id="ref-neyman23app" class="csl-entry" role="listitem">
Neyman, J. (1923). Sur les applications de la thar des probabilities aux experiences agaricales: Essay des principle. Excerpts reprinted (1990) in <span>E</span>nglish. <em>Statistical Science</em>, <em>5</em>, 463–472.
</div>
<div id="ref-robins86new" class="csl-entry" role="listitem">
Robins, J. M. (1986). A new approach to causal inference in mortality studies with sustained exposure periods – application to control of the healthy worker survivor effect. <em>Mathematical Modeling</em>, <em>7</em>, 1393–1512.
</div>
<div id="ref-robins94estimation" class="csl-entry" role="listitem">
Robins, J. M., Rotnitzky, A., &amp; Zhao, L. P. (1994). Estimation of regression coefficients when some regressors are not always observed. <em>Journal of the American Statistical Association</em>, <em>89</em>, 846–866.
</div>
<div id="ref-rosenbaum1987sensitivity" class="csl-entry" role="listitem">
Rosenbaum, P. R. (1987). Sensitivity analysis for certain permutation inferences in matched observational studies. <em>Biometrika</em>, <em>74</em>(1), 13–26.
</div>
<div id="ref-rosenbaum83propensity" class="csl-entry" role="listitem">
Rosenbaum, P. R., &amp; Rubin, D. B. (1983). The central role of the propensity score in observational studies for causal effects. <em>Biometrika</em>, <em>70</em>, 41–55.
</div>
<div id="ref-rubin74potential" class="csl-entry" role="listitem">
Rubin, D. B. (1974). Estimating causal effects of treatments in randomized and non-randomized studies. <em>Journal of Educational Psychology</em>, <em>66</em>, 688–701.
</div>
<div id="ref-tan2006distributional" class="csl-entry" role="listitem">
Tan, Z. (2006). A distributional approach for causal inference using propensity scores. <em>Journal of the American Statistical Association</em>, <em>101</em>(476), 1619–1637.
</div>
<div id="ref-vanderweele2011bias" class="csl-entry" role="listitem">
VanderWeele, T. J., &amp; Arah, O. A. (2011). Bias formulas for sensitivity analysis of unmeasured confounding for general outcomes, treatments, and confounders. <em>Epidemiology</em>, 42–52.
</div>
<div id="ref-zhao2019sensitivity" class="csl-entry" role="listitem">
Zhao, Q., Small, D. S., &amp; Bhattacharya, B. B. (2019). Sensitivity analysis for inverse probability weighting estimators via the percentile bootstrap. <em>Journal of the Royal Statistical Society: Series B</em>, <em>81</em>(4), 735–761.
</div>
</div>
</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
  window.document.addEventListener("DOMContentLoaded", function (event) {
    const icon = "";
    const anchorJS = new window.AnchorJS();
    anchorJS.options = {
      placement: 'right',
      icon: icon
    };
    anchorJS.add('.anchored');
    const isCodeAnnotation = (el) => {
      for (const clz of el.classList) {
        if (clz.startsWith('code-annotation-')) {                     
          return true;
        }
      }
      return false;
    }
    const onCopySuccess = function(e) {
      // button target
      const button = e.trigger;
      // don't keep focus
      button.blur();
      // flash "checked"
      button.classList.add('code-copy-button-checked');
      var currentTitle = button.getAttribute("title");
      button.setAttribute("title", "Copied!");
      let tooltip;
      if (window.bootstrap) {
        button.setAttribute("data-bs-toggle", "tooltip");
        button.setAttribute("data-bs-placement", "left");
        button.setAttribute("data-bs-title", "Copied!");
        tooltip = new bootstrap.Tooltip(button, 
          { trigger: "manual", 
            customClass: "code-copy-button-tooltip",
            offset: [0, -8]});
        tooltip.show();    
      }
      setTimeout(function() {
        if (tooltip) {
          tooltip.hide();
          button.removeAttribute("data-bs-title");
          button.removeAttribute("data-bs-toggle");
          button.removeAttribute("data-bs-placement");
        }
        button.setAttribute("title", currentTitle);
        button.classList.remove('code-copy-button-checked');
      }, 1000);
      // clear code selection
      e.clearSelection();
    }
    const getTextToCopy = function(trigger) {
      const outerScaffold = trigger.parentElement.cloneNode(true);
      const codeEl = outerScaffold.querySelector('code');
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
    const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
      text: getTextToCopy
    });
    clipboard.on('success', onCopySuccess);
    if (window.document.getElementById('quarto-embedded-source-code-modal')) {
      const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
        text: getTextToCopy,
        container: window.document.getElementById('quarto-embedded-source-code-modal')
      });
      clipboardModal.on('success', onCopySuccess);
    }
    const viewSource = window.document.getElementById('quarto-view-source') ||
                       window.document.getElementById('quarto-code-tools-source');
    if (viewSource) {
      const sourceUrl = viewSource.getAttribute("data-quarto-source-url");
      viewSource.addEventListener("click", function(e) {
        if (sourceUrl) {
          // rstudio viewer pane
          if (/\bcapabilities=\b/.test(window.location)) {
            window.open(sourceUrl);
          } else {
            window.location.href = sourceUrl;
          }
        } else {
          const modal = new bootstrap.Modal(document.getElementById('quarto-embedded-source-code-modal'));
          modal.show();
        }
        return false;
      });
    }
    function toggleCodeHandler(show) {
      return function(e) {
        const detailsSrc = window.document.querySelectorAll(".cell > details > .sourceCode");
        for (let i=0; i<detailsSrc.length; i++) {
          const details = detailsSrc[i].parentElement;
          if (show) {
            details.open = true;
          } else {
            details.removeAttribute("open");
          }
        }
        const cellCodeDivs = window.document.querySelectorAll(".cell > .sourceCode");
        const fromCls = show ? "hidden" : "unhidden";
        const toCls = show ? "unhidden" : "hidden";
        for (let i=0; i<cellCodeDivs.length; i++) {
          const codeDiv = cellCodeDivs[i];
          if (codeDiv.classList.contains(fromCls)) {
            codeDiv.classList.remove(fromCls);
            codeDiv.classList.add(toCls);
          } 
        }
        return false;
      }
    }
    const hideAllCode = window.document.getElementById("quarto-hide-all-code");
    if (hideAllCode) {
      hideAllCode.addEventListener("click", toggleCodeHandler(false));
    }
    const showAllCode = window.document.getElementById("quarto-show-all-code");
    if (showAllCode) {
      showAllCode.addEventListener("click", toggleCodeHandler(true));
    }
      var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var mailtoRegex = new RegExp(/^mailto:/);
        var filterRegex = new RegExp('/' + window.location.host + '/');
      var isInternal = (href) => {
          return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
      }
      // Inspect non-navigation links and adorn them if external
     var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
      for (var i=0; i<links.length; i++) {
        const link = links[i];
        if (!isInternal(link.href)) {
          // undo the damage that might have been done by quarto-nav.js in the case of
          // links that we want to consider external
          if (link.dataset.originalHref !== undefined) {
            link.href = link.dataset.originalHref;
          }
        }
      }
    function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
      const config = {
        allowHTML: true,
        maxWidth: 500,
        delay: 100,
        arrow: false,
        appendTo: function(el) {
            return el.parentElement;
        },
        interactive: true,
        interactiveBorder: 10,
        theme: 'quarto',
        placement: 'bottom-start',
      };
      if (contentFn) {
        config.content = contentFn;
      }
      if (onTriggerFn) {
        config.onTrigger = onTriggerFn;
      }
      if (onUntriggerFn) {
        config.onUntrigger = onUntriggerFn;
      }
      window.tippy(el, config); 
    }
    const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
    for (var i=0; i<noterefs.length; i++) {
      const ref = noterefs[i];
      tippyHover(ref, function() {
        // use id or data attribute instead here
        let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
        try { href = new URL(href).hash; } catch {}
        const id = href.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note) {
          return note.innerHTML;
        } else {
          return "";
        }
      });
    }
    const xrefs = window.document.querySelectorAll('a.quarto-xref');
    const processXRef = (id, note) => {
      // Strip column container classes
      const stripColumnClz = (el) => {
        el.classList.remove("page-full", "page-columns");
        if (el.children) {
          for (const child of el.children) {
            stripColumnClz(child);
          }
        }
      }
      stripColumnClz(note)
      if (id === null || id.startsWith('sec-')) {
        // Special case sections, only their first couple elements
        const container = document.createElement("div");
        if (note.children && note.children.length > 2) {
          container.appendChild(note.children[0].cloneNode(true));
          for (let i = 1; i < note.children.length; i++) {
            const child = note.children[i];
            if (child.tagName === "P" && child.innerText === "") {
              continue;
            } else {
              container.appendChild(child.cloneNode(true));
              break;
            }
          }
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(container);
          }
          return container.innerHTML
        } else {
          if (window.Quarto?.typesetMath) {
            window.Quarto.typesetMath(note);
          }
          return note.innerHTML;
        }
      } else {
        // Remove any anchor links if they are present
        const anchorLink = note.querySelector('a.anchorjs-link');
        if (anchorLink) {
          anchorLink.remove();
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        if (note.classList.contains("callout")) {
          return note.outerHTML;
        } else {
          return note.innerHTML;
        }
      }
    }
    for (var i=0; i<xrefs.length; i++) {
      const xref = xrefs[i];
      tippyHover(xref, undefined, function(instance) {
        instance.disable();
        let url = xref.getAttribute('href');
        let hash = undefined; 
        if (url.startsWith('#')) {
          hash = url;
        } else {
          try { hash = new URL(url).hash; } catch {}
        }
        if (hash) {
          const id = hash.replace(/^#\/?/, "");
          const note = window.document.getElementById(id);
          if (note !== null) {
            try {
              const html = processXRef(id, note.cloneNode(true));
              instance.setContent(html);
            } finally {
              instance.enable();
              instance.show();
            }
          } else {
            // See if we can fetch this
            fetch(url.split('#')[0])
            .then(res => res.text())
            .then(html => {
              const parser = new DOMParser();
              const htmlDoc = parser.parseFromString(html, "text/html");
              const note = htmlDoc.getElementById(id);
              if (note !== null) {
                const html = processXRef(id, note);
                instance.setContent(html);
              } 
            }).finally(() => {
              instance.enable();
              instance.show();
            });
          }
        } else {
          // See if we can fetch a full url (with no hash to target)
          // This is a special case and we should probably do some content thinning / targeting
          fetch(url)
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.querySelector('main.content');
            if (note !== null) {
              // This should only happen for chapter cross references
              // (since there is no id in the URL)
              // remove the first header
              if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
                note.children[0].remove();
              }
              const html = processXRef(null, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      }, function(instance) {
      });
    }
        let selectedAnnoteEl;
        const selectorForAnnotation = ( cell, annotation) => {
          let cellAttr = 'data-code-cell="' + cell + '"';
          let lineAttr = 'data-code-annotation="' +  annotation + '"';
          const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
          return selector;
        }
        const selectCodeLines = (annoteEl) => {
          const doc = window.document;
          const targetCell = annoteEl.getAttribute("data-target-cell");
          const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
          const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
          const lines = annoteSpan.getAttribute("data-code-lines").split(",");
          const lineIds = lines.map((line) => {
            return targetCell + "-" + line;
          })
          let top = null;
          let height = null;
          let parent = null;
          if (lineIds.length > 0) {
              //compute the position of the single el (top and bottom and make a div)
              const el = window.document.getElementById(lineIds[0]);
              top = el.offsetTop;
              height = el.offsetHeight;
              parent = el.parentElement.parentElement;
            if (lineIds.length > 1) {
              const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
              const bottom = lastEl.offsetTop + lastEl.offsetHeight;
              height = bottom - top;
            }
            if (top !== null && height !== null && parent !== null) {
              // cook up a div (if necessary) and position it 
              let div = window.document.getElementById("code-annotation-line-highlight");
              if (div === null) {
                div = window.document.createElement("div");
                div.setAttribute("id", "code-annotation-line-highlight");
                div.style.position = 'absolute';
                parent.appendChild(div);
              }
              div.style.top = top - 2 + "px";
              div.style.height = height + 4 + "px";
              div.style.left = 0;
              let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
              if (gutterDiv === null) {
                gutterDiv = window.document.createElement("div");
                gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
                gutterDiv.style.position = 'absolute';
                const codeCell = window.document.getElementById(targetCell);
                const gutter = codeCell.querySelector('.code-annotation-gutter');
                gutter.appendChild(gutterDiv);
              }
              gutterDiv.style.top = top - 2 + "px";
              gutterDiv.style.height = height + 4 + "px";
            }
            selectedAnnoteEl = annoteEl;
          }
        };
        const unselectCodeLines = () => {
          const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
          elementsIds.forEach((elId) => {
            const div = window.document.getElementById(elId);
            if (div) {
              div.remove();
            }
          });
          selectedAnnoteEl = undefined;
        };
          // Handle positioning of the toggle
      window.addEventListener(
        "resize",
        throttle(() => {
          elRect = undefined;
          if (selectedAnnoteEl) {
            selectCodeLines(selectedAnnoteEl);
          }
        }, 10)
      );
      function throttle(fn, ms) {
      let throttle = false;
      let timer;
        return (...args) => {
          if(!throttle) { // first call gets through
              fn.apply(this, args);
              throttle = true;
          } else { // all the others get throttled
              if(timer) clearTimeout(timer); // cancel #2
              timer = setTimeout(() => {
                fn.apply(this, args);
                timer = throttle = false;
              }, ms);
          }
        };
      }
        // Attach click handler to the DT
        const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
        for (const annoteDlNode of annoteDls) {
          annoteDlNode.addEventListener('click', (event) => {
            const clickedEl = event.target;
            if (clickedEl !== selectedAnnoteEl) {
              unselectCodeLines();
              const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
              if (activeEl) {
                activeEl.classList.remove('code-annotation-active');
              }
              selectCodeLines(clickedEl);
              clickedEl.classList.add('code-annotation-active');
            } else {
              // Unselect the line
              unselectCodeLines();
              clickedEl.classList.remove('code-annotation-active');
            }
          });
        }
    const findCites = (el) => {
      const parentEl = el.parentElement;
      if (parentEl) {
        const cites = parentEl.dataset.cites;
        if (cites) {
          return {
            el,
            cites: cites.split(' ')
          };
        } else {
          return findCites(el.parentElement)
        }
      } else {
        return undefined;
      }
    };
    var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
    for (var i=0; i<bibliorefs.length; i++) {
      const ref = bibliorefs[i];
      const citeInfo = findCites(ref);
      if (citeInfo) {
        tippyHover(citeInfo.el, function() {
          var popup = window.document.createElement('div');
          citeInfo.cites.forEach(function(cite) {
            var citeDiv = window.document.createElement('div');
            citeDiv.classList.add('hanging-indent');
            citeDiv.classList.add('csl-entry');
            var biblioDiv = window.document.getElementById('ref-' + cite);
            if (biblioDiv) {
              citeDiv.innerHTML = biblioDiv.innerHTML;
            }
            popup.appendChild(citeDiv);
          });
          return popup.innerHTML;
        });
      }
    }
  });
  </script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="../../chapters/chapter7/index.html" class="pagination-link" aria-label="Mediation Analysis">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text"><span class="chapter-number">7</span>&nbsp; <span class="chapter-title">Mediation Analysis</span></span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="../../chapters/chapter9/index.html" class="pagination-link" aria-label="Discussion">
        <span class="nav-page-text"><span class="chapter-number">9</span>&nbsp; <span class="chapter-title">Discussion</span></span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->
<footer class="footer">
  <div class="nav-footer">
    <div class="nav-footer-left">
<p>Computational Causal Inference for Applied Researchers, M.A.&nbsp;Luque-Fernandez &amp; M.J. Smith</p>
</div>   
    <div class="nav-footer-center">
      &nbsp;
    <div class="toc-actions d-sm-block d-md-none"><ul><li><a href="https://github.com/migariane/Causal-Inference-Book/edit/main/chapters/chapter8/index.qmd" class="toc-action"><i class="bi bi-github"></i>Edit this page</a></li><li><a href="https://github.com/migariane/Causal-Inference-Book/issues/new" class="toc-action"><i class="bi empty"></i>Report an issue</a></li><li><a href="https://github.com/migariane/Causal-Inference-Book/blob/main/chapters/chapter8/index.qmd" class="toc-action"><i class="bi empty"></i>View source</a></li></ul></div></div>
    <div class="nav-footer-right">
<p>© 2026 Universidad de Granada</p>
</div>
  </div>
</footer>




<script src="../../site_libs/quarto-html/zenscroll-min.js"></script>
</body></html>